name: Build and Deploy
on: [ push ]

jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USER }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USER }}/todolist:latest

  deploy:
    runs-on: ubuntu-latest
#    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy files on server
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            source: "deploy/*"
            target: "todolist"
            strip_components: 1